# Generated by Django 5.0.2 on 2024-02-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
    ]
