# Generated by Django 5.0.2 on 2024-02-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
